name: Build Infra for MLflow Model Deployment

on:
  push:
    branches:
      - master
  workflow_dispatch:
env:
  DOCKER_IMAGE_NAME: mlflowformldeploy
  DOCKER_REGISTRY_URL: "index.docker.io"

jobs: 
  build-docker-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.DOCKER_REGISTRY_URL }}
          username: ${{ secrets.INFRA_DOCKER_REGISTRY_USERNAME }}
          password: ${{ secrets.INFRA_DOCKER_REGISTRY_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: mlflow_for_ml_deployment
          push: true
          tags: ${{ env.DOCKER_REGISTRY_URL }}/${{ env.DOCKER_IMAGE_NAME }}:${{ github.sha }}


      
  # terraform:
  #   runs-on: ubuntu-latest
  #   env: 
  #     ARM_CLIENT_ID: ${{ secrets.INFRA_AZURE_AD_CLIENT_ID }}
  #     ARM_CLIENT_SECRET: ${{ secrets.INFRA_AZURE_AD_CLIENT_SECRET }}
  #     ARM_SUBSCRIPTION_ID: ${{ secrets.INFRA_AZURE_SUBSCRIPTION_ID }}
  #     ARM_TENANT_ID: ${{ secrets.INFRA_AZURE_AD_TENANT_ID }}
  #     TF_VERSION: 1.5.7
  #     TERRAFORM_WORKING_DIR: "mlflow_for_ml_deployment"
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v2

  #     - name: 'Terraform Format'
  #       uses: hashicorp/terraform-github-actions@master
  #       with:
  #         tf_actions_version: ${{ env.TF_VERSION }}
  #         tf_actions_subcommand: 'fmt'
  #         tf_actions_working_dir: ${{ env.TERRAFORM_WORKING_DIR }}

  #     - name: 'Terraform Init'
  #       uses: hashicorp/terraform-github-actions@master
  #       with:
  #         tf_actions_version: ${{ env.TF_VERSION }}
  #         tf_actions_subcommand: 'init'
  #         tf_actions_working_dir: ${{ env.TERRAFORM_WORKING_DIR }}
  #       env:
  #         TF_VAR_resource_group_name: ${{ vars.ABCD_AZURE_RESOURCE_GROUP_NAME }}
  #         TF_VAR_location: ${{ vars.ABCD_AZURE_RG_LOCATION }}
  #         TF_VAR_docker_registry_username: ${{ secrets.INFRA_DOCKER_REGISTRY_USERNAME }}
  #         TF_VAR_docker_registry_password: ${{ secrets.INFRA_DOCKER_REGISTRY_PASSWORD }}

  #     - name: 'Terraform Validate'
  #       uses: hashicorp/terraform-github-actions@master
  #       with:
  #         tf_actions_version: ${{ env.TF_VERSION }}
  #         tf_actions_subcommand: 'validate'
  #         tf_actions_working_dir: ${{ env.TERRAFORM_WORKING_DIR }}
          
  #     - name: 'Terraform Plan'
  #       uses: hashicorp/terraform-github-actions@master
  #       with:
  #         tf_actions_version: ${{ env.TF_VERSION }}
  #         tf_actions_subcommand: 'plan'
  #         tf_actions_working_dir: ${{ env.TERRAFORM_WORKING_DIR }}
  #       env:
  #         TF_VAR_resource_group_name: ${{ vars.ABCD_AZURE_RESOURCE_GROUP_NAME }}
  #         TF_VAR_location: ${{ vars.ABCD_AZURE_RG_LOCATION }}
  #         TF_VAR_docker_registry_username: ${{ secrets.INFRA_DOCKER_REGISTRY_USERNAME }}
  #         TF_VAR_docker_registry_password: ${{ secrets.INFRA_DOCKER_REGISTRY_PASSWORD }}
      
  #     - name: Terraform Apply
  #       if: github.ref == 'refs/heads/master'
  #       uses: hashicorp/terraform-github-actions@master
  #       with:
  #         tf_actions_version: ${{ env.TF_VERSION }}
  #         tf_actions_subcommand: 'apply'
  #         tf_actions_working_dir: ${{ env.TERRAFORM_WORKING_DIR }}
  #       env:
  #         TF_VAR_resource_group_name: ${{ vars.ABCD_AZURE_RESOURCE_GROUP_NAME }}
  #         TF_VAR_location: ${{ vars.ABCD_AZURE_RG_LOCATION }}
  #         TF_VAR_docker_registry_username: ${{ secrets.INFRA_DOCKER_REGISTRY_USERNAME }}
  #         TF_VAR_docker_registry_password: ${{ secrets.INFRA_DOCKER_REGISTRY_PASSWORD }}
          